### ISSUE TITLE
Deficiency Report: Page elements cannot be aligned

### ISSUE THREAD

**Issue by jackyliu16** [alexanderdavide/slidev-theme-academic#11] opened 2023-03-13 16:15 UTC
I was trying to use your theme for my panel debriefing, and when I'm trying to run the `example.md` file in the right ways, page 2 and 3 which indicate table-of-contents of page jump and index shows a misalignment between ordinal and text, which is different with screenshot on README.

> by the ways, the last one index has not arise this problem, but this kinds of problem could be discover in the [Older files](https://delta-in-hub.github.io/slidev-intro/1)

![image](https://user-images.githubusercontent.com/50787361/224760780-b9fdc278-9e75-4207-a39a-c958268e3f6f.png)
![image](https://user-images.githubusercontent.com/50787361/224760798-9c780876-ddc7-423a-8187-55439f02a3cc.png)
![image](https://user-images.githubusercontent.com/50787361/224760817-acaba8dc-21d7-45f8-b193-8385cd2c596e.png)

**Comment by alexanderdavide** [comment] 2023-03-15 19:19
Hey, happy to see you're using slidev-theme-academic and thanks for reporting this bug!

Currently, I can't reproduce this bug running the latest v0.40.3 of @slidev/cli on Linux and Chromium. Can you please provide details on your slidev version, operating system and browser?

**Comment by jackyliu16** [comment] 2023-03-16 06:28
Though my simple check and review, I find that the issue maybe is occurred with the browser, when I reopen the [old Folder](https://delta-in-hub.github.io/slidev-intro/1), the view of tab-of-content is diff in different browser.
The default browser of two computers is **Firefox**, thus have this problem? I also ask a friend for help, he also found this issue.
![image](https://user-images.githubusercontent.com/50787361/225532959-34a93b6c-5f9f-4376-95bc-164d5a8cf703.png)
![image](https://user-images.githubusercontent.com/50787361/225533157-5e4cc8d2-3d59-4ab0-85ba-2f02e8f8c693.png)

**Comment by alexanderdavide** [comment] 2023-03-18 10:21
Indeed, I'm able to reproduce this on Firefox.

However, I have to forward you to slidev's source directly because both layouts [index](https://github.com/alexanderdavide/slidev-theme-academic/blob/master/layouts/index.vue) and [table-of-contents](https://github.com/alexanderdavide/slidev-theme-academic/blob/master/layouts/table-of-contents.vue) rely on components originating from slidev, namely [Toc](https://github.com/slidevjs/slidev/blob/main/packages/client/builtin/Toc.vue) and [TocList](https://github.com/slidevjs/slidev/blob/main/packages/client/builtin/TocList.vue). There existed an issue for this problem slidevjs/slidev#655 but the maintainers didn't consider it.

Finally, I'm closing the issue here because the problem roots in slidev itself.

**Closed by alexanderdavide** 2023-03-18 10:21 UTC
