### ISSUE TITLE
pagination and footnote will overlap together when export to pdf

### ISSUE THREAD

**Issue by Delta-in-hub** [alexanderdavide/slidev-theme-academic#7] opened 2022-12-02 03:34 UTC
![2022-12-02_11-32](https://user-images.githubusercontent.com/53047182/205208976-4f020c3c-574b-426d-8e25-5c12965e8ee7.png)

```bash
npx slidev export
```

**Comment by Delta-in-hub** [comment] 2022-12-02 03:46
https://github.com/Delta-in-hub/Delta-in-hub.github.io/blob/master/slidev-intro/slidev-intro.md

This is an example.

**Comment by alexanderdavide** [comment] 2022-12-13 16:17
Hey, thanks for using the theme and reporting this issue!

What a coincidence: The same day you opened the issue, I was trying to export a presentation and experienced the overlapping too.

After some investigation, it seems the issue is caused by #slidevjs/slidev513 introduced in @slidev/cli [v0.30.0](https://github.com/slidevjs/slidev/releases/tag/v0.30.0) as well as me using `position: fixed` in components `Footnotes`, `Pagination` and layout `cover`. Previous to this version, the export had worked as expected.

This issue should be resolved with #8.

**Closed** 2022-12-21 19:56 UTC

**Comment by alexanderdavide** [comment] 2022-12-21 20:04
#8 is included in the latest release [v.1.1.1](https://github.com/alexanderdavide/slidev-theme-academic/releases/tag/1.1.1).
