### ISSUE TITLE
$setup.$slidev is undefined

### ISSUE THREAD

**Issue by klieret** [alexanderdavide/slidev-theme-academic#4] opened 2022-07-30 18:45 UTC
Thanks a lot for creating this beautiful theme!

Unfortunately I am unable to use it.

I've created a small repository to demonstrate the issue: https://github.com/klieret/slidev-academic-bug-demo

The file `console_export.txt` contains the output of the firefox console.

But basically I do 

```bash
npm init slidev@latest
# remove most of the slides.md and update the theme to use yours
npx slidev
# install theme
```

And nothing shows up at all.

Browser is firefox, on a M1 Mac, slidev version 0.35.2

**Comment by alexanderdavide** [comment] 2022-08-03 16:10
Thank you very much for reporting the issue. This really helps me to keep the theme alive and functioning.

I was able to reproduce this using any version of the latest minor release of Slidev being 0.35.*. The problem stems from Slidev internals. Recently, there has been opened an issue, slidevjs/slidev#672, that targets the root cause of the error you're experiencing.

For the time being, you can pin Slidev to version < 0.35. I've tried 0.34.3 successfully. I'll investigate further if I need change something on my end.

I'm happy you like the theme and hope you can enjoy it further!

**Comment by klieret** [comment] 2022-08-03 18:42
Thanks a lot! Let me try this :)

**Comment by alexanderdavide** [comment] 2022-08-06 08:54
Closing as the issue is with Slidev and is going to be fixed in upcoming releases.

**Closed by alexanderdavide** 2022-08-06 08:54 UTC
